import Head from 'next/head'
import { useContext } from 'react';
import { ReadProfile } from '../components';
import { MainContext } from '../context';
import styles from '../styles/Home.module.css'

export default function Home() {

  const { currentAccount, connectWallet } = useContext(MainContext);

  const getTruncatedAddress = (
    address,
    length
  ) => {
    if (!address) {
      return '';
    }

    return `${address.slice(0, length + 2)}...${address.slice(
      address.length - length
    )}`;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Ceramic Playground</title>
        <meta name="description" content="Generated by Ropats" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1 className={styles.title}>
          Welcome to Ceramic Playground!
        </h1>
        <br />
        {currentAccount ?
          (<div>
            Connected Wallet: {getTruncatedAddress(currentAccount, 3)}
          </div>
          ) :
          (
            <button className={styles.button} onClick={connectWallet}>
              Connect Wallet
            </button>
          )
        }
      </header>
      <main className={styles.main}>
        <ReadProfile />
      </main>
    </div>
  )
}
